---
# defaults file for awx_on_k3s
awx_on_k3s_awx_host: awx.example.com
awx_on_k3s_awx_admin_pass: 'Password1234!'
awx_on_k3s_galaxy_host: galaxy.example.com
awx_on_k3s_galaxy_admin_pass: 'Password1234!'
awx_on_k3s_eda_host: eda.example.com
awx_on_k3s_eda_admin_pass: 'Password1234!'
awx_on_k3s_awx_dirs:
  - path: /data/postgres-15/data
    owner: "26:0"
    mode: "0700"
  - path: /data/projects
    owner: "1000:0"
    mode: "0755"
...
