---
# defaults file for awx_on_k3s
awx_on_k3s_awx_host: awx.example.com
awx_on_k3s_awx_admin_pass: 'Password1234!'
awx_on_k3s_galaxy_host: galaxy.example.com
awx_on_k3s_galaxy_admin_pass: 'Password1234!'
awx_on_k3s_eda_host: eda.example.com
awx_on_k3s_eda_admin_pass: 'Password1234!'
awx_on_k3s_deployment_dir: /awx_on_k3s
awx_on_k3s_deploy_k3s: true
awx_on_k3s_disable_services:
  - firewalld
  - nm-cloud-setup.service
  - nm-cloud-setup.timer
awx_on_k3s_hosts_lines:
  - "{{ ansible_facts['default_ipv4']['address'] }} {{ awx_on_k3s_awx_host }}"
  - "{{ ansible_facts['default_ipv4']['address'] }} {{ awx_on_k3s_galaxy_host }}"
  - "{{ ansible_facts['default_ipv4']['address'] }} {{ awx_on_k3s_eda_host }}"
...
