---
# handlers file for awx_on_k3s
- name: Reboot
  ansible.builtin.reboot:

- name: Daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

...
