---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ awx_on_k3s_deployment_dir }}"
    state: directory
    mode: "0755"

- name: Copy base config
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ awx_on_k3s_deployment_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - operator
    - base

- name: Deploy AWX Operator
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir=operator_dir) }}"
  vars:
    operator_dir: "{{ awx_on_k3s_deployment_dir }}/operator"

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ awx_on_k3s_deployment_dir }}/base/tls.key"

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ awx_on_k3s_deployment_dir }}/base/tls.key"
    common_name: "{{ awx_on_k3s_awx_host }}"
    subject_alt_name:
      - "DNS:{{ awx_on_k3s_awx_host }}"
  register: csr

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ awx_on_k3s_deployment_dir }}/base/tls.crt"
    csr_content: "{{ csr.csr }}"
    privatekey_path: "{{ awx_on_k3s_deployment_dir }}/base/tls.key"
    provider: selfsigned

- name: Ensure awx.yaml config is good
  ansible.builtin.template:
    src: "awx/{{ item }}.yaml.j2"
    dest: "{{ awx_on_k3s_deployment_dir }}/base/{{ item }}.yaml"
    mode: "0644"
  loop:
    - awx
    - kustomization

- name: Ensure directories exist and have correct permissions
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: directory
    owner: "{{ item['owner'] }}"
    mode: "{{ item['mode'] }}"
  loop: "{{ awx_on_k3s_awx_dirs }}"

- name: Deploy AWX
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir=base_dir) }}"
  vars:
    base_dir: "{{ awx_on_k3s_deployment_dir }}/base/"

...
