---
- name: Create directory .kube
  ansible.builtin.file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="
  delegate_to: localhost
  become: false

- name: Copy config file to user home directory
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    mode: "0640"
...
