---
- name: Add lines to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop: "{{ awx_on_k3s_hosts_lines }}"

- name: Install dnsmasq
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Start dnsmasq with default configuration
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true

- name: Ensure directory paths exist
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: Create new resolv.conf to use K3s
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/resolv.conf
    content: "nameserver {{ ansible_facts['default_ipv4']['address'] }}"
    mode: "0644"

- name: Do daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

...
